version: '3'

services:
  db:
    image: postgres:14.1
    container_name: TT_DB
    ports: 
      - "5435:5432"
    volumes:
      - "./data/postgres_data:/var/lib/postgresql/data/"
    env_file:
      - database.env
    networks:
      - techtrends
  bytebase:
    image: bytebase/bytebase:0.10.0
    container_name: TT_DB_CLIENT
    restart: always
    volumes:
      - "./data/bytebase:/var/opt/bytebase"
    ports:
      - "5678:80"
    networks:
    - techtrends
  
networks:
  techtrends:
    driver: bridge