version: '3'

services:
  collector:
    build: 
      dockerfile: ./docker-conf/collector/Dockerfile
      context: .
    container_name: TT_COLLECTOR
    volumes:
      - ./collector:/data/collector
    env_file: 
      - collector/.env
    networks:
      - techtrends
  db:
    image: postgres:14.1
    container_name: TT_DB
    ports: 
      - "5435:5432"
    volumes:
      - "./data/postgres_data:/var/lib/postgresql/data/"
    env_file:
      - database.env
    networks:
      - techtrends
  pgweb:
    image: sosedoff/pgweb
    container_name: TT_DB_CLIENT
    restart: always
    ports:
      - "8089:8081"
    links: 
      - db:db  # my database container is called postgres, not db
    networks:
      - techtrends
    env_file: 
      - database.env
    depends_on:
      - db
  
networks:
  techtrends:
    driver: bridge